### PR TITLE
added bugreport support

### PR DESCRIPTION
**Pull request by vvscloud**

### CODE REVIEW

**Comment by vmalyi** [comment]
Proposed change (https://github.com/vvscloud/adb_android/pull/2) which should fix travis execution

**Comment by vmalyi** [comment]
@vvscloud could you please also update [README.MD](https://github.com/vmalyi/adb_android/blob/master/README.md) with changes you made?

Thanks!

**Comment by vvscloud** [comment]
Sure. I will update readme.md and also other changes you have mentioned.

**Comment by vvscloud** [comment]
Changes updated. Please merge.

**Pull request merged**
